# Generated by Django 4.0.1 on 2022-01-26 00:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_contact_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
